name: Broadcast IP Test

on:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:

      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      
      - name: Ping broadcast
        run: |
          ping 255.255.255.255 -c 5
