name: Broadcast IP Test

on:
  workflow_dispatch:

jobs:
  enum:
    runs-on: ubuntu-latest
    steps:

      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Enable broadcast 
        run: |
         echo "before"
         sudo sysctl net.ipv4.icmp_echo_ignore_broadcasts
         
         echo "after"
         sudo sysctl net.ipv4.icmp_echo_ignore_broadcasts=0
         sudo sysctl net.ipv4.icmp_echo_ignore_broadcasts
         
      
      - run: |
         sudo apt install socat
         socat -h
      # - name: Ping broadcast
      #   run: |
      #     ping -c 5 255.255.255.255
          
