name: Bulk API

on:
  workflow_dispatch:

jobs:
  bulk-request:
    runs-on: ubuntu-latest
    steps:
        
      - uses: step-security/harden-runner@rc
        with:
         egress-policy: block
         allowed-endpoints: |
            google.com:443
            youtube.com:443
            example1.com:443
            example2.com:443
            example3.com:443
            example4.com:443
            example5.com:443
            example6.com:443
            example7.com:443
            example8.com:443
            example9.com:443
            example10.com:443
            example11.com:443
            example12.com:443
            example13.com:443
            example14.com:443
            example15.com:443
            example16.com:443
            example17.com:443
            example18.com:443
            example19.com:443
            example20.com:443
            example21.com:443
            example22.com:443
            example23.com:443
            example24.com:443
            example25.com:443
            example26.com:443
            example27.com:443
            example28.com:443
            example29.com:443
            example30.com:443
            example31.com:443
            example32.com:443
            example33.com:443
            example34.com:443
            example35.com:443
            example36.com:443
            example37.com:443
            example38.com:443
            example39.com:443
            example40.com:443
            example41.com:443
            example42.com:443
            example43.com:443
            example44.com:443
            example45.com:443
            example46.com:443
            example47.com:443
            example48.com:443
            example49.com:443
            example50.com:443
            example51.com:443
            example52.com:443
            example53.com:443
            example54.com:443
            example55.com:443
            example56.com:443
            example57.com:443
            example58.com:443
            example59.com:443
            example60.com:443
            example61.com:443
            example62.com:443
            example63.com:443
            example64.com:443
            example65.com:443
            example66.com:443
            example67.com:443
            example68.com:443
            example69.com:443
            example70.com:443
            example71.com:443
            example72.com:443
            example73.com:443
            example74.com:443
            example75.com:443
            example76.com:443
            example77.com:443
            example78.com:443
            example79.com:443
            example80.com:443
            example81.com:443
            example82.com:443
            example83.com:443
            example84.com:443
            example85.com:443
            example86.com:443
            example87.com:443
            example88.com:443
            example89.com:443
            example90.com:443
            example91.com:443
            example92.com:443
            example93.com:443
            example94.com:443
            example95.com:443
            example96.com:443
            example97.com:443
            example98.com:443
            example99.com:443
            example100.com:443
            example101.com:443
            example102.com:443
            example103.com:443
            example104.com:443
            example105.com:443
            example106.com:443
            example107.com:443
            example108.com:443
            example109.com:443
            example110.com:443
            example111.com:443
            example112.com:443
            example113.com:443
            example114.com:443
            example115.com:443
         
      - name: Generate 
        run: |
          for i in {1..300}; do
            domain="example${i}.com"
            ip="192.168.2.${i}"
            curl --resolve "${domain}:443:${ip}" --connect-timeout 2 --max-time 3 "https://${domain}"
          done
               
