name: Bulk API

on:
  workflow_dispatch:

jobs:
  bulk-request:
    runs-on: ubuntu-latest
    steps:
        
      - uses: step-security/harden-runner@rc
        with:
         egress-policy: block
         allowed-endpoints: |
            example1.com:80
            example2.com:80
            example3.com:80
            example4.com:80
            example5.com:80
            example6.com:80
            example7.com:80
            example8.com:80
            example9.com:80
            example10.com:80
            example11.com:80
            example12.com:80
            example13.com:80
            example14.com:80
            example15.com:80
            example16.com:80
            example17.com:80
            example18.com:80
            example19.com:80
            example20.com:80
            example21.com:80
            example22.com:80
            example23.com:80
            example24.com:80
            example25.com:80
            example26.com:80
            example27.com:80
            example28.com:80
            example29.com:80
            example30.com:80
            example31.com:80
            example32.com:80
            example33.com:80
            example34.com:80
            example35.com:80
            example36.com:80
            example37.com:80
            example38.com:80
            example39.com:80
            example40.com:80
            example41.com:80
            example42.com:80
            example43.com:80
            example44.com:80
            example45.com:80
            example46.com:80
            example47.com:80
            example48.com:80
            example49.com:80
            example50.com:80
            example51.com:80
            example52.com:80
            example53.com:80
            example54.com:80
            example55.com:80
            example56.com:80
            example57.com:80
            example58.com:80
            example59.com:80
            example60.com:80
            example61.com:80
            example62.com:80
            example63.com:80
            example64.com:80
            example65.com:80
            example66.com:80
            example67.com:80
            example68.com:80
            example69.com:80
            example70.com:80
            example71.com:80
            example72.com:80
            example73.com:80
            example74.com:80
            example75.com:80
            example76.com:80
            example77.com:80
            example78.com:80
            example79.com:80
            example80.com:80
            example81.com:80
            example82.com:80
            example83.com:80
            example84.com:80
            example85.com:80
            example86.com:80
            example87.com:80
            example88.com:80
            example89.com:80
            example90.com:80
            example91.com:80
            example92.com:80
            example93.com:80
            example94.com:80
            example95.com:80
            example96.com:80
            example97.com:80
            example98.com:80
            example99.com:80
            example100.com:80
            example101.com:80
            example102.com:80
            example103.com:80
            example104.com:80
            example105.com:80
            example106.com:80
            example107.com:80
            example108.com:80
            example109.com:80
            example110.com:80
            example111.com:80
            example112.com:80
            example113.com:80
            example114.com:80
            example115.com:80
            example116.com:80
            example117.com:80
            example118.com:80
            example119.com:80
            example120.com:80
            example121.com:80
            example122.com:80
            example123.com:80
            example124.com:80
            example125.com:80
            example126.com:80
            example127.com:80
            example128.com:80
            example129.com:80
            example130.com:80
            example131.com:80
            example132.com:80
            example133.com:80
            example134.com:80
            example135.com:80
            example136.com:80
            example137.com:80
            example138.com:80
            example139.com:80
            example140.com:80
            example141.com:80
            example142.com:80
            example143.com:80
            example144.com:80
            example145.com:80
            example146.com:80
            example147.com:80
            example148.com:80
            example149.com:80
            example150.com:80
            example151.com:80
            example152.com:80
            example153.com:80
            example154.com:80
            example155.com:80
            example156.com:80
            example157.com:80
            example158.com:80
            example159.com:80
            example160.com:80
            example161.com:80
            example162.com:80
            example163.com:80
            example164.com:80
            example165.com:80
            example166.com:80
            example167.com:80
            example168.com:80
            example169.com:80
            example170.com:80
            example171.com:80
            example172.com:80
            example173.com:80
            example174.com:80
            example175.com:80
            example176.com:80
            example177.com:80
            example178.com:80
            example179.com:80
            example180.com:80
            example181.com:80
            example182.com:80
            example183.com:80
            example184.com:80
            example185.com:80
            example186.com:80
            example187.com:80
            example188.com:80
            example189.com:80
            example190.com:80
            example191.com:80
            example192.com:80
            example193.com:80
            example194.com:80
            example195.com:80
            example196.com:80
            example197.com:80
            example198.com:80
            example199.com:80
            example200.com:80
            example201.com:80
            example202.com:80
            example203.com:80
            example204.com:80
            example205.com:80
            example206.com:80
            example207.com:80
            example208.com:80
            example209.com:80
            example210.com:80
            example211.com:80
            example212.com:80
            example213.com:80
            example214.com:80
            example215.com:80
            example216.com:80
            example217.com:80
            example218.com:80
            example219.com:80
            example220.com:80
            example221.com:80
            example222.com:80
            example223.com:80
            example224.com:80
            example225.com:80
            example226.com:80
            example227.com:80
            example228.com:80
            example229.com:80
            example230.com:80
            example231.com:80
            example232.com:80
            example233.com:80
            example234.com:80
            example235.com:80
            example236.com:80
            example237.com:80
            example238.com:80
            example239.com:80
            example240.com:80
            example241.com:80
            example242.com:80
            example243.com:80
            example244.com:80
            example245.com:80
            example246.com:80
            example247.com:80
            example248.com:80
            example249.com:80
            example250.com:80
            example251.com:80
            example252.com:80
            example253.com:80
            example254.com:80
            example255.com:80
            example256.com:80
            example257.com:80
            example258.com:80
            example259.com:80
            example260.com:80
            example261.com:80
            example262.com:80
            example263.com:80
            example264.com:80
            example265.com:80
            example266.com:80
            example267.com:80
            example268.com:80
            example269.com:80
            example270.com:80
            example271.com:80
            example272.com:80
            example273.com:80
            example274.com:80
            example275.com:80
            example276.com:80
            example277.com:80
            example278.com:80
            example279.com:80
            example280.com:80
            example281.com:80
            example282.com:80
            example283.com:80
            example284.com:80
            example285.com:80
            example286.com:80
            example287.com:80
            example288.com:80
            example289.com:80
            example290.com:80
            example291.com:80
            example292.com:80
            example293.com:80
            example294.com:80
            example295.com:80
            example296.com:80
            example297.com:80
            example298.com:80
            example299.com:80
            example300.com:80
         
      - name: Generate 
        run: |
          sudo cp /etc/hosts /etc/hosts.backup
          for i in {1..500}; do
            domain="example${i}.com"
            ip="192.168.2.${i}"
            echo "${ip} ${domain}" | sudo tee -a /etc/hosts > /dev/null
          done
          
          for i in {1..500}; do
            domain="example${i}.com"
            ip="192.168.2.${i}"
            (curl --connect-timeout 2 --max-time 3 "http://${domain}" || true)&
          done
          sleep 200
               
