name: Bulk API

on:
  workflow_dispatch:

jobs:
  bulk-request:
    runs-on: ubuntu-latest
    steps:
        
      - uses: step-security/harden-runner@rc
        with:
         egress-policy: block
         allowed-endpoints: |
            google.com:80
            youtube.com:80
            example1.com:80
            example2.com:80
            example3.com:80
            example4.com:80
            example5.com:80
            example6.com:80
            example7.com:80
            example8.com:80
            example9.com:80
            example10.com:80
            example11.com:80
            example12.com:80
            example13.com:80
            example14.com:80
            example15.com:80
            example16.com:80
            example17.com:80
            example18.com:80
            example19.com:80
            example20.com:80
            example21.com:80
            example22.com:80
            example23.com:80
            example24.com:80
            example25.com:80
            example26.com:80
            example27.com:80
            example28.com:80
            example29.com:80
            example30.com:80
            example31.com:80
            example32.com:80
            example33.com:80
            example34.com:80
            example35.com:80
            example36.com:80
            example37.com:80
            example38.com:80
            example39.com:80
            example40.com:80
            example41.com:80
            example42.com:80
            example43.com:80
            example44.com:80
            example45.com:80
            example46.com:80
            example47.com:80
            example48.com:80
            example49.com:80
            example50.com:80
            example51.com:80
            example52.com:80
            example53.com:80
            example54.com:80
            example55.com:80
            example56.com:80
            example57.com:80
            example58.com:80
            example59.com:80
            example60.com:80
            example61.com:80
            example62.com:80
            example63.com:80
            example64.com:80
            example65.com:80
            example66.com:80
            example67.com:80
            example68.com:80
            example69.com:80
            example70.com:80
            example71.com:80
            example72.com:80
            example73.com:80
            example74.com:80
            example75.com:80
            example76.com:80
            example77.com:80
            example78.com:80
            example79.com:80
            example80.com:80
            example81.com:80
            example82.com:80
            example83.com:80
            example84.com:80
            example85.com:80
            example86.com:80
            example87.com:80
            example88.com:80
            example89.com:80
            example90.com:80
            example91.com:80
            example92.com:80
            example93.com:80
            example94.com:80
            example95.com:80
            example96.com:80
            example97.com:80
            example98.com:80
            example99.com:80
            example100.com:80
            example101.com:80
            example102.com:80
            example103.com:80
            example104.com:80
            example105.com:80
            example106.com:80
            example107.com:80
            example108.com:80
            example109.com:80
            example110.com:80
            example111.com:80
            example112.com:80
            example113.com:80
            example114.com:80
            example115.com:80
         
      - name: Generate 
        run: |
          sudo cp /etc/hosts /etc/hosts.backup
          for i in {1..250}; do
            domain="example${i}.com"
            ip="192.168.2.${i}"
            echo "${ip} ${domain}" | sudo tee -a /etc/hosts > /dev/null
          done
          
          for i in {1..300}; do
            domain="example${i}.com"
            ip="192.168.2.${i}"
            (curl --resolve "${domain}:80:${ip}" --connect-timeout 2 --max-time 3 "http://${domain}" || true)&
          done
          sleep 120
               
