name: Call IMDS Endpoint

on:
  workflow_dispatch: {}

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
         egress-policy: audit

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Fetch instance metadata (IMDS)
        run: |
          curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/ || true
