name: Docker Image CI

on:
  workflow_dispatch:
    

jobs:

  build:
    runs-on: ARMLinuxRunner
    #runs-on: [self-hosted, ec2]
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
        egress-policy: audit
        allowed-endpoints: >
          auth.docker.io:443
          database.clamav.net:443
          current.cvd.clamav.net:443
          files.pythonhosted.org:443
          github.com:443
          production.cloudflare.docker.com:443
          pypi.org:443
          registry-1.docker.io:443

    - uses: actions/checkout@v2
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile
