name: Upload and Download Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: |
            github.com:443
            *.githubusercontent.com:443
            *.internal.cloudapp.net:443
            *.github.com:443


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact file
        run: |
          echo "Hello from the build job!" > output.txt

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output.txt

  consume:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: |
            github.com:443

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Read artifact content
        run: |
          echo "Contents of artifact:"
          cat output.txt
