name: Set up Local Kubernetes with k3d and containerd

on:
  workflow_dispatch:

jobs:
  setup-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
        egress-policy: audit
        
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install k3d (lightweight wrapper to run K3s in Docker)
    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    # Create a Kubernetes cluster using k3d
    - name: Create k3d cluster
      run: |
        k3d cluster create mycluster --wait
        k3d cluster list  # List the clusters to ensure it's up and running

    # Verify Kubernetes cluster is up and running
    - name: Verify connection to cluster
      run: kubectl get nodes

    # Apply your Kubernetes deployment
    - name: Deploy app to local k8s cluster
      run: |
        kubectl apply -f k8s/deployment.yml  # Ensure your deployment YAML is in the k8s folder
        kubectl rollout status deployment/your-deployment-name

    # Check pods using containerd runtime
    - name: Check pods running in containerd
      run: |
        kubectl get pods -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.containerStatuses[0].containerID}{"\n"}{end}'
