name: Large Matrix Workflow2

on:
  workflow_dispatch:
    inputs:
      print_count:
        description: 'Number of times to print (1000 or 3000)'
        required: true
        default: '1000' # Default value as a string
  pull_request:

jobs:
  setup-job:
    name: Setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int-sh
        with:
          egress-policy: audit

      - name: Sleep for 20 seconds
        run: sleep 20

  generate-jobs:
    name: Generate Jobs
    needs: setup-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int-sh
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Make a curl request
        run: curl https://google.com
      
      - name: Print large amount of text
        run: |
          echo "This is job number ${{ matrix.job_id }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            print_count=1000
          else
            print_count="${{ github.event.inputs.print_count }}"
          fi
          for i in $(seq 1 "$print_count"); do
            echo "Logging text line $i for job ${{ matrix.job_id }}: $(head -c 100 < /dev/urandom | tr -dc 'A-Za-z0-9');"
          done
