name: Tailscale

on: 
  workflow_dispatch:

jobs:
  test-host-outbound:
    runs-on: ubuntu-latest
    steps:
      
            
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - run: cat /run/systemd/resolve/resolv.conf
      - run: cat /etc/resolv.conf
      - name: Checkout code
        uses: actions/checkout@v3
