name: Trigger outbound calls by infra process

on:
  workflow_dispatch: {}

jobs:
  outbound-call:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@int
        with:
         egress-policy: audit

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Schedule heartbeat cron
        run: |
          # Create a cron file; user 'runner' exists on ubuntu-latest
          echo "* * * * * runner curl -fsS -X POST http://example.com/heartbeat >/dev/null 2>&1" \
            | sudo tee /etc/cron.d/heartbeat-job
          sudo chmod 644 /etc/cron.d/heartbeat-job

          # Reload cron so it picks up the new job
          sudo service cron reload

      - name: Do other work
        run: |
          echo "Cron daemon PID: $(pgrep cron)"
          echo "Cron daemon PPID: $(ps -o ppid= -p $(pgrep cron))"
          echo "Cron is now firing every minute in the background..."
          sleep 90   # keep the job alive long enough to see it run
