name: 2. Exfiltration Simulation
on:
  workflow_dispatch:

jobs:
  exfiltration-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: >
            *:443

      - uses: actions/checkout@v3

      # Dependency Confusion DNS Exfiltration Scenario
      - name: DNS Exfiltration
        run: dig google.com
      
      # Codecov Scenario: Exfiltrate data to attacker's endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: curl pastebin.com -L
